# Change these first
owner: heymaslo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: OpenAI
    url: https://www.openai.com
  - name: Storymapr
    url: https://www.storymapr.com
  - name: MongoDb
    url: https://www.mongodb.com
  - name: AWS
    url: https://amazon.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/31329337?s=200&v=4
  name: maslo Status Page
  introTitle: "**Maslo**"
  introMessage: Check the status of the services here
  navbar:
    - title: Status
      href: /status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
